
# window variables
WINDOW_NAME = "SmartNode"
WINDOW_X_POS = 300
WINDOW_Y_POS = 100
WINDOW_W_RATIO = 5/8
WINDOW_L_RATIO = 7/8

BUTTON_HEIGHT = -90
BUTTON_WIDTH = -600

WINDOW_W, WINDOW_L = WINDOW_SIZE = 800, 480
